SELECT 
    YEAR(A.SALES_DATE) AS YEAR,
    MONTH(A.SALES_DATE) AS MONTH,
    B.GENDER AS GENDER,
    COUNT(DISTINCT A.USER_ID) AS USER_COUNT
FROM 
    ONLINE_SALE A
LEFT OUTER JOIN 
    USER_INFO B 
ON 
    A.USER_ID = B.USER_ID
WHERE 
    B.GENDER IS NOT NULL
GROUP BY 
    YEAR(A.SALES_DATE), 
    MONTH(A.SALES_DATE), 
    B.GENDER
ORDER BY 
    YEAR ASC, 
    MONTH ASC, 
    GENDER ASC;
