SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (
    SELECT MAX(A.LENGTH)
    FROM FISH_INFO A
    WHERE A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH > 10
)
ORDER BY A.ID;